name: "Tests"

on:
  workflow_call:
  workflow_dispatch:
  merge_group:

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

jobs:
  run-pytest:
    env:
      ARCH_NAME: wormhole_b0
      TT_METAL_HOME: ${pwd}
      PYTHONPATH: ${pwd}
    runs-on: ["in-service", "n150"]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Where Am I?
        run: ls
      - name: Run Tests
        run: pytest tests/*.py
