name: "Tests"

on:
  workflow_call:
  workflow_dispatch:
  merge_group:

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

jobs:
  run-pytest:
    env:
      ARCH_NAME: wormhole_b0
      TT_METAL_HOME: ${pwd}
      PYTHONPATH: ${pwd}
    runs-on: ["in-service", "n150"]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip config set global.extra-index-url https://download.pytorch.org/whl/cpu
          python3 -m pip install --upgrade pip          
          python3 -m pip install -r requirements.txt      
      - name: Run Tests
        run: | 
          source venv/bin/activate
          python3 -m pytest tests/*.py
