name: "hello world workflow"

on:
  workflow_call:
  workflow_dispatch:
  pull_request:    
    branches: [ "main" ]
  merge_group:
    types: [checks_requested]

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

jobs:
  hello-world:
    runs-on: ["in-service", "n150"]
    steps:
      - name: Sample Action
        run: echo "Action run!"    
