name: Pull Request Validation

on:
  pull_request:

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Black
        uses: psf/black@23.10.1
